import { ActionButton } from './PasteArea'

/**
 * What the right-hand column says before any data is loaded.
 *
 * The previous empty state was one sentence telling the user to do something.
 * This says what the tool is for, what it will show them, and gives them the
 * one-click route to seeing it — because a merit tool is much easier to
 * understand with a population in it than described in the abstract.
 */
export function GettingStarted({
  onLoadSample,
  hasGrades,
  hasEmployees,
}: {
  onLoadSample: () => void
  hasGrades: boolean
  hasEmployees: boolean
}) {
  const halfLoaded = hasGrades !== hasEmployees

  return (
    <div className="rounded border border-zinc-200 bg-white px-6 py-6">
      {halfLoaded ? (
        <p className="mb-5 rounded border border-amber-200 bg-amber-50 px-3 py-2 text-xs leading-relaxed text-amber-900">
          {hasEmployees
            ? 'A population is loaded, but there is no salary structure to place it against. Paste one on the left, or load the sample to see both.'
            : 'A salary structure is loaded, but there is nobody in it yet. Paste a population on the left, or load the sample.'}
        </p>
      ) : null}

      <h2 className="text-sm font-medium text-zinc-900">
        Design a merit matrix and watch what it does.
      </h2>
      <p className="mt-1.5 max-w-2xl text-xs leading-relaxed text-zinc-600">
        Most merit modelling answers one question: what does this cost. Merit Lab
        answers that on every keystroke, and then answers the ones that follow —
        where it moves your population, who it pushes past a range maximum, who
        it leaves below a minimum, and what it does to the steps between your
        grades.
      </p>

      <ol className="mt-5 space-y-3">
        <Step
          number={1}
          title="Load a population"
          body="Paste a CSV or a column range straight out of a spreadsheet. It needs an employee id, a grade, a base salary and a rating; anything else you bring becomes a dimension you can break results down by."
        />
        <Step
          number={2}
          title="Design the matrix"
          body="Rows are ratings, columns are compa-ratio bands. Type a percentage into any cell. Underneath it you will see what that cell costs, which is usually the number that changes the plan."
        />
        <Step
          number={3}
          title="Read the consequences"
          body="Cost, variance to target, where every employee lands, who ends up outside their range, and a ranked list of what to do about it. All of it recomputes as you type; there is no Calculate button because there is no server to wait for."
        />
      </ol>

      <div className="mt-5 flex flex-wrap items-center gap-3">
        <ActionButton onClick={onLoadSample}>Load the sample population</ActionButton>
        <span className="text-[11px] text-zinc-500">
          204 synthetic employees and an eight-grade structure, generated by code.
        </span>
      </div>

      <p className="mt-5 border-t border-zinc-100 pt-3 text-[11px] leading-relaxed text-zinc-500">
        Nothing you paste leaves this browser. There is no server, no account and
        no storage: close the tab and it is gone. Export a scenario file if you
        want to keep one.
      </p>
    </div>
  )
}

function Step({
  number,
  title,
  body,
}: {
  number: number
  title: string
  body: string
}) {
  return (
    <li className="flex gap-3">
      <span className="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full border border-zinc-300 text-[10px] tabular-nums text-zinc-500">
        {number}
      </span>
      <div className="min-w-0">
        <div className="text-xs font-medium text-zinc-900">{title}</div>
        <p className="mt-0.5 max-w-2xl text-[11px] leading-relaxed text-zinc-600">
          {body}
        </p>
      </div>
    </li>
  )
}
