import { useMemo, useState } from 'react'
import { Panel, Stat } from './components/Panel'
import { IssueList } from './components/IssueList'
import { GradeProfileTable } from './components/GradeProfileTable'
import { PasteArea, ActionButton } from './components/PasteArea'
import { importEmployeesFromCsv } from './lib/import-employees'
import { importGradesFromCsv } from './lib/import-grades'
import { profilePopulation } from './lib/population-profile'
import {
  formatCompaRatio,
  formatCount,
  formatCurrencyCompact,
  formatPercent,
  pluralize,
} from './lib/format'
import { SAMPLE_POPULATION } from './data/sample-population'
import { SAMPLE_GRADES } from './data/sample-structure'
import type { ImportIssue } from './lib/import-employees'

const POPULATION_PLACEHOLDER = `employee_id,grade,base_salary,performance_rating,fte,eligible,hire_date
E001,G3,74500,Meets,1,Y,2019-04-01
E002,G5,103000,Exceeds,0.8,Y,2022-11-15`

const STRUCTURE_PLACEHOLDER = `grade,name,order,min,mid,max
G1,Analyst,1,51000,60000,69000
G2,Senior Analyst,2,56500,67000,77500`

export default function App() {
  const [populationText, setPopulationText] = useState('')
  const [structureText, setStructureText] = useState('')
  const [sampleLoaded, setSampleLoaded] = useState(false)

  // Everything below recomputes on every keystroke. There is no server, so
  // there is nothing that could be loading and no reason to make anyone wait.
  const structureImport = useMemo(
    () => (structureText.trim() ? importGradesFromCsv(structureText) : null),
    [structureText],
  )

  const grades =
    structureImport && structureImport.grades.length > 0
      ? structureImport.grades
      : sampleLoaded
        ? SAMPLE_GRADES
        : []

  const populationImport = useMemo(
    () =>
      populationText.trim()
        ? importEmployeesFromCsv(populationText, {
            knownGradeIds: grades.length > 0 ? grades.map((g) => g.id) : undefined,
          })
        : null,
    [populationText, grades],
  )

  const employees =
    populationImport?.employees ?? (sampleLoaded ? SAMPLE_POPULATION : [])

  const profile = useMemo(
    () => profilePopulation(employees, grades),
    [employees, grades],
  )

  const errors: ImportIssue[] = [
    ...(structureImport?.errors ?? []),
    ...(populationImport?.errors ?? []),
  ]
  const warnings: ImportIssue[] = [
    ...(structureImport?.warnings ?? []),
    ...(populationImport?.warnings ?? []),
  ]

  const hasData = employees.length > 0 && grades.length > 0

  const loadSample = () => {
    setSampleLoaded(true)
    setPopulationText('')
    setStructureText('')
  }

  const clearAll = () => {
    setSampleLoaded(false)
    setPopulationText('')
    setStructureText('')
  }

  return (
    <div className="min-h-screen bg-zinc-50 text-zinc-900">
      <header className="border-b border-zinc-200 px-6 py-3">
        <div className="mx-auto flex max-w-7xl items-baseline justify-between gap-6">
          <h1 className="text-sm font-semibold tracking-tight">Merit Lab</h1>
          <p className="text-[11px] text-zinc-500">
            Runs entirely in your browser. Nothing you paste is uploaded, transmitted,
            or stored.
          </p>
        </div>
      </header>

      <main className="mx-auto grid max-w-7xl grid-cols-1 gap-10 px-6 py-8 lg:grid-cols-[minmax(0,22rem)_minmax(0,1fr)]">
        {/* Controls */}
        <div>
          <Panel
            title="Population"
            aside={
              employees.length > 0
                ? `${formatCount(profile.eligibleCount)} eligible`
                : undefined
            }
          >
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-medium tabular-nums">
                {formatCount(employees.length)}
              </span>
              <span className="text-sm text-zinc-500">
                {employees.length === 1 ? 'employee' : 'employees'}
              </span>
            </div>

            <div className="mt-3 flex gap-2">
              <ActionButton onClick={loadSample}>Load sample</ActionButton>
              <ActionButton
                onClick={clearAll}
                disabled={!sampleLoaded && !populationText && !structureText}
              >
                Clear
              </ActionButton>
            </div>

            {sampleLoaded && !populationText ? (
              <p className="mt-3 text-[11px] leading-relaxed text-zinc-500">
                Showing a synthetic 204-employee population, generated by code. It
                deliberately includes green-circled, red-circled, part-time and
                ineligible employees.
              </p>
            ) : null}
          </Panel>

          <Panel title="Paste population">
            <PasteArea
              label="Paste population data"
              value={populationText}
              onChange={setPopulationText}
              placeholder={POPULATION_PLACEHOLDER}
              rows={7}
            />
            <p className="mt-2 text-[11px] leading-relaxed text-zinc-400">
              CSV or a column range copied from a spreadsheet. Needs an id, grade,
              base salary and rating; FTE, eligibility and hire date are optional.
              Any other column becomes a grouping you can break results down by.
            </p>
          </Panel>

          <Panel
            title="Salary structure"
            aside={grades.length > 0 ? pluralize(grades.length, 'grade') : undefined}
          >
            <PasteArea
              label="Paste salary structure"
              value={structureText}
              onChange={setStructureText}
              placeholder={STRUCTURE_PLACEHOLDER}
              rows={6}
            />
            <p className="mt-2 text-[11px] leading-relaxed text-zinc-400">
              Needs a grade code, minimum and maximum. Midpoint is derived from the
              range if you leave it out. Order is derived from midpoint if you leave
              it out, and it will say so.
            </p>
          </Panel>
        </div>

        {/* Consequences */}
        <div>
          {hasData ? (
            <>
              <Panel title="Profile">
                <div className="grid grid-cols-2 gap-6 sm:grid-cols-4">
                  <Stat
                    label="Eligible payroll"
                    value={formatCurrencyCompact(profile.eligiblePayroll)}
                    detail={`of ${formatCurrencyCompact(profile.totalPayroll)} total`}
                  />
                  <Stat
                    label="Median compa-ratio"
                    value={formatCompaRatio(profile.medianCompaRatio)}
                    detail={`mean ${formatCompaRatio(profile.meanCompaRatio)}`}
                  />
                  <Stat
                    label="Below minimum"
                    value={formatCount(profile.belowMinimum)}
                    detail={
                      profile.headcount > 0
                        ? formatPercent(profile.belowMinimum / profile.headcount, 1)
                        : undefined
                    }
                    tone={profile.belowMinimum > 0 ? 'warn' : 'quiet'}
                  />
                  <Stat
                    label="Above maximum"
                    value={formatCount(profile.aboveMaximum)}
                    detail={
                      profile.headcount > 0
                        ? formatPercent(profile.aboveMaximum / profile.headcount, 1)
                        : undefined
                    }
                    tone={profile.aboveMaximum > 0 ? 'warn' : 'quiet'}
                  />
                </div>

                {profile.unplaceable > 0 ? (
                  <p className="mt-4 text-xs text-amber-800">
                    {pluralize(profile.unplaceable, 'employee')} could not be placed
                    in a range and {profile.unplaceable === 1 ? 'is' : 'are'} left out
                    of every average. They are still counted in headcount and payroll.
                  </p>
                ) : null}
              </Panel>

              <Panel title="By grade">
                <GradeProfileTable profile={profile} grades={grades} />
              </Panel>

              <Panel title="Rating distribution">
                <RatingBars profile={profile} />
              </Panel>
            </>
          ) : (
            <EmptyState hasGrades={grades.length > 0} hasEmployees={employees.length > 0} />
          )}

          {errors.length > 0 || warnings.length > 0 ? (
            <Panel title="Import notes">
              <IssueList errors={errors} warnings={warnings} />
            </Panel>
          ) : null}
        </div>
      </main>
    </div>
  )
}

function RatingBars({ profile }: { profile: ReturnType<typeof profilePopulation> }) {
  const total = profile.headcount
  const widest = Math.max(...profile.ratingCounts.map((r) => r.count), 1)

  return (
    <div className="space-y-1.5">
      {profile.ratingCounts.map(({ rating, count }) => (
        <div key={rating} className="flex items-center gap-3 text-xs">
          <div className="w-28 shrink-0 truncate text-zinc-600">{rating}</div>
          <div className="h-3 flex-1 bg-zinc-100">
            <div
              className="h-full bg-zinc-400"
              style={{ width: `${(count / widest) * 100}%` }}
            />
          </div>
          <div className="w-10 shrink-0 text-right tabular-nums text-zinc-900">
            {formatCount(count)}
          </div>
          <div className="w-12 shrink-0 text-right tabular-nums text-zinc-400">
            {formatPercent(total > 0 ? count / total : null, 0)}
          </div>
        </div>
      ))}
    </div>
  )
}

function EmptyState({
  hasGrades,
  hasEmployees,
}: {
  hasGrades: boolean
  hasEmployees: boolean
}) {
  let message = 'Load the sample population, or paste your own data on the left.'
  if (hasEmployees && !hasGrades) {
    message =
      'A population is loaded but there is no salary structure to place it against. Paste a structure on the left.'
  } else if (hasGrades && !hasEmployees) {
    message = 'A salary structure is loaded. Paste a population to place against it.'
  }

  return (
    <div className="rounded border border-dashed border-zinc-300 px-6 py-12 text-center">
      <p className="text-sm text-zinc-500">{message}</p>
    </div>
  )
}
