import type { Employee } from '../types/domain'
import { SAMPLE_GRADES } from './sample-structure'

/**
 * A synthetic population of 204 employees.
 *
 * SYNTHETIC. Every figure is generated by the code below. No real pay data
 * appears in this repository, and none ever will.
 *
 * Deterministic: the same seed produces the same population on every run, so the
 * tests can assert exact figures and the numbers on your screen match the
 * numbers in the test file.
 *
 * The population is deliberately awkward. It contains green-circled and
 * red-circled employees, part-timers, ineligible employees, and recent hires,
 * because a sample where every path through the maths goes untested would make
 * the tool look like it works when it has not been asked a hard question.
 */

/** The rating scale, strongest first. */
export const SAMPLE_RATINGS = [
  'Exceeds',
  'Strong',
  'Meets',
  'Developing',
  'Below',
] as const

/**
 * An OBSERVED rating distribution, not a guideline one.
 *
 * Merit Lab never enforces a distribution: ratings arrive as data. These weights
 * shape the synthetic sample only, and they are deliberately inflated relative
 * to a textbook guideline, because real populations drift upward. Half the
 * population sits in the top two boxes and almost nobody is in the bottom one.
 */
const RATING_WEIGHTS: Record<string, number> = {
  Exceeds: 0.18,
  Strong: 0.32,
  Meets: 0.44,
  Developing: 0.05,
  Below: 0.01,
}

/** Headcount per grade: a pyramid, thinning toward the top. */
const HEADCOUNT_BY_GRADE: Record<string, number> = {
  G1: 34,
  G2: 38,
  G3: 36,
  G4: 30,
  G5: 24,
  G6: 20,
  G7: 14,
  G8: 8,
}

/**
 * Employees are placed by RANGE PENETRATION, not by compa-ratio.
 *
 * Drawing compa-ratio directly would green-circle far too many people in the
 * junior grades: this structure's grade 1 minimum sits at 0.85 compa-ratio while
 * grade 8's sits at 0.76, so one distribution of compa-ratios produces wildly
 * different out-of-range rates by grade. Penetration is measured against each
 * grade's own width, so a single distribution behaves sensibly everywhere.
 *
 * Centred a little below the range midpoint, which is where populations usually
 * sit once hiring below midpoint and slow range movement have done their work.
 */
const PENETRATION_MEAN = 0.44
const PENETRATION_SD = 0.24

/** Share of the population hired inside the last twelve months. */
const RECENT_HIRE_RATE = 0.08
/** The performance period these sample hire dates are drawn against. */
const SAMPLE_PERIOD_END_YEAR = 2025

const DEPARTMENTS = ['Operations', 'Finance', 'Technology', 'Commercial', 'People']
const LOCATIONS = ['Head Office', 'Regional', 'Remote']

/**
 * Deterministic pseudo-random generator (mulberry32).
 *
 * Math.random cannot be used here: the sample must be identical on every run so
 * the tests can assert against it.
 */
function createRandom(seed: number): () => number {
  let state = seed
  return () => {
    state |= 0
    state = (state + 0x6d2b79f5) | 0
    let t = Math.imul(state ^ (state >>> 15), 1 | state)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/** Two uniform draws into one roughly normal draw, mean 0, sd 1. */
function normalDraw(random: () => number): number {
  const u1 = Math.max(random(), 1e-9)
  const u2 = random()
  return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2)
}

function pickWeighted(random: () => number, weights: Record<string, number>): string {
  const roll = random()
  let cumulative = 0
  for (const [key, weight] of Object.entries(weights)) {
    cumulative += weight
    if (roll < cumulative) return key
  }
  const keys = Object.keys(weights)
  return keys[keys.length - 1]
}

function isoDate(year: number, month: number, day: number): string {
  return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
}

/**
 * Generate the sample population.
 *
 * Salary is derived from a drawn range penetration and rounded to the nearest
 * 100, as a real salary would be. Part-time employees carry ACTUAL pay: a 0.5
 * FTE employee placed at midpoint holds half the midpoint as their base salary.
 */
export function generateSamplePopulation(seed = 20_250_101): Employee[] {
  const random = createRandom(seed)
  const employees: Employee[] = []
  let sequence = 1

  for (const grade of SAMPLE_GRADES) {
    const headcount = HEADCOUNT_BY_GRADE[grade.id]
    const width = grade.max - grade.min

    for (let i = 0; i < headcount; i++) {
      const id = `EMP-${String(sequence).padStart(4, '0')}`
      sequence++

      // Placement within this grade's own range. Not clamped: the tails are the
      // green-circled and red-circled employees, and they are wanted.
      const penetration = PENETRATION_MEAN + normalDraw(random) * PENETRATION_SD
      const fullTimeSalary = Math.round((grade.min + penetration * width) / 100) * 100

      // About one employee in twenty is part-time.
      const fte = random() < 0.05 ? [0.5, 0.6, 0.8][Math.floor(random() * 3)] : 1
      const baseSalary = Math.round((fullTimeSalary * fte) / 100) * 100

      // Most tenure is spread across fifteen years; a deliberate tail was hired
      // inside the last twelve months, so proration has something to act on.
      const isRecentHire = random() < RECENT_HIRE_RATE
      const hireYear = isRecentHire
        ? SAMPLE_PERIOD_END_YEAR - 1
        : SAMPLE_PERIOD_END_YEAR - 2 - Math.floor(random() * 14)
      const hireMonth = 1 + Math.floor(random() * 12)
      const hireDay = 1 + Math.floor(random() * 28)

      // About three percent are ineligible.
      const eligible = random() >= 0.03

      employees.push({
        id,
        gradeId: grade.id,
        baseSalary,
        performanceRating: pickWeighted(random, RATING_WEIGHTS),
        fte,
        eligible,
        hireDate: isoDate(hireYear, hireMonth, hireDay),
        attributes: {
          department: DEPARTMENTS[Math.floor(random() * DEPARTMENTS.length)],
          location: LOCATIONS[Math.floor(random() * LOCATIONS.length)],
        },
      })
    }
  }

  return employees
}

/** The default sample, generated once. */
export const SAMPLE_POPULATION: Employee[] = generateSamplePopulation()
